import AVFoundation
import Foundation
import LatheCore
import LatheFixtures
import Testing

@testable import LatheAudio

/// Tests for the audio prober, against clips generated by `LatheFixtures`.
///
/// Serialised because every test encodes or decodes media; a dozen of those at
/// once makes the machine the bottleneck and the timings meaningless.
@Suite("Audio inspection", .serialized)
struct AudioInspectorTests {

    private let inspector = AudioInspector()

    // MARK: - Duration

    /// The question this type was added to answer, and the reason it is answered
    /// against a fixture of *known* length rather than against a file somebody
    /// once made.
    @Test("duration is the length the fixture was written at")
    func durationMatchesTheFixture() async throws {
        guard let wav = await fixture("audio-duration.wav", {
            try await FixtureLibrary.shared.wav(
                named: "audio-duration.wav", seconds: 3.5,
                audio: .tone(hertz: 440, amplitude: 0.4)
            )
        }) else { return }

        let seconds = try await inspector.duration(of: wav)
        // A WAV's duration is sample-exact; the tolerance is for the rounding in
        // `seconds * sampleRate`, not for any codec's delay.
        #expect(abs(seconds - 3.5) < 0.01)

        let info = try await inspector.inspect(wav)
        #expect(abs(info.duration - 3.5) < 0.01)
        #expect(info.hasDeterminateDuration)
        #expect(abs((info.stream?.duration ?? 0) - 3.5) < 0.01)
    }

    // MARK: - Lossless and lossy

    /// The distinction the whole module turns on, in both directions.
    @Test("PCM reads as lossless and AAC reads as lossy")
    func losslessIsDistinguishedFromLossy() async throws {
        guard let wav = await fixture("audio-pcm.wav", {
            try await FixtureLibrary.shared.wav(
                named: "audio-pcm.wav", seconds: 2, audio: .tone(hertz: 440, amplitude: 0.4)
            )
        }), let aac = await fixture("audio-lossy.m4a", {
            try await FixtureLibrary.shared.aacFile(named: "audio-lossy.m4a", seconds: 2)
        }) else { return }

        let pcm = try #require(try await inspector.inspect(wav).stream)
        #expect(pcm.codecName == "pcm")
        #expect(pcm.isLossless)
        #expect(!pcm.isLossy)
        #expect(pcm.bitDepth == 16)

        let lossy = try #require(try await inspector.inspect(aac).stream)
        #expect(lossy.codecName == "aac")
        #expect(!lossy.isLossless)
        // A compressed stream has no bit depth, and reporting 0 as if it were
        // one is how "16-bit AAC" gets into a UI.
        #expect(lossy.bitDepth == nil)
    }

    // MARK: - The numbers a decision is made from

    @Test("rate, channels and bitrate are reported from the container")
    func reportsTheShapeOfTheStream() async throws {
        guard let aac = await fixture("audio-shape.m4a", {
            try await FixtureLibrary.shared.aacFile(
                named: "audio-shape.m4a", seconds: 4,
                bitsPerSecond: 128_000, sampleRate: 44_100, channels: 2
            )
        }) else { return }

        let stream = try #require(try await inspector.inspect(aac).stream)
        #expect(stream.sampleRate == 44_100)
        #expect(stream.channelCount == 2)
        #expect(!stream.isMultichannel)

        let bitrate = try #require(stream.bitsPerSecond)
        // Wide, because an encoder asked for 128 kbit/s delivers roughly that
        // and a container adds its own bytes. Narrow enough to catch a
        // bits/bytes confusion, which is the mistake that would actually break
        // the lossy-source rule.
        #expect(bitrate > 90_000)
        #expect(bitrate < 190_000)
    }

    @Test("a low-rate mono source is reported as low-rate and mono")
    func reportsNarrowSources() async throws {
        guard let wav = await fixture("audio-narrow.wav", {
            try await FixtureLibrary.shared.wav(
                named: "audio-narrow.wav", seconds: 2,
                audio: .tone(hertz: 440, amplitude: 0.4),
                sampleRate: 22_050, channels: 1
            )
        }) else { return }

        let stream = try #require(try await inspector.inspect(wav).stream)
        #expect(stream.sampleRate == 22_050)
        #expect(stream.channelCount == 1)
    }

    /// The layout is not decoration: without one, a multi-channel re-encode is
    /// impossible, and ``ChannelPolicy`` documents what happens instead.
    @Test("a multi-channel source carries a channel layout")
    func multichannelCarriesALayout() async throws {
        guard let surround = await fixture("audio-surround.caf", {
            try await FixtureLibrary.shared.multichannelPCM(
                named: "audio-surround.caf", seconds: 1, channels: 6
            )
        }) else { return }

        let stream = try #require(try await inspector.inspect(surround).stream)
        #expect(stream.channelCount == 6)
        #expect(stream.isMultichannel)
        #expect(stream.isLossless)
        #expect(stream.channelLayout != nil)
    }

    // MARK: - No audio, and no file

    @Test("a file with no audio track is a fact, not an error")
    func noAudioTrackIsNotAnError() async throws {
        guard let movie = await fixture("audio-silent-video.mov", {
            try await FixtureLibrary.shared.movie(named: "audio-silent-video.mov", audio: .none)
        }) else { return }

        let info = try await inspector.inspect(movie)
        #expect(info.stream == nil)
        #expect(!info.hasAudioTrack)
        // ...and the duration is still answerable, which is the point of
        // separating the two.
        #expect(info.duration > 1.5)
    }

    @Test("a chapterless file reports no chapters")
    func chapterCountIsZeroWithoutChapters() async throws {
        guard let aac = await fixture("audio-nochapters.m4a", {
            try await FixtureLibrary.shared.aacFile(named: "audio-nochapters.m4a", seconds: 1)
        }) else { return }

        #expect(try await inspector.inspect(aac).chapterCount == 0)
    }

    @Test("a file that is not media fails, rather than reporting an empty one")
    func notMediaThrows() async throws {
        guard let url = await fixture("audio-not-media.m4a", {
            try await FixtureLibrary.shared.notMedia(named: "audio-not-media.m4a")
        }) else { return }

        await #expect(throws: LatheError.self) { _ = try await inspector.inspect(url) }
    }

    @Test("a missing file fails as a read error")
    func missingFileThrows() async throws {
        let missing = await FixtureLibrary.shared.scratchURL(named: "audio-absent.m4a")
        await #expect(throws: LatheError.self) { _ = try await inspector.duration(of: missing) }
    }

    // MARK: - Codec naming

    /// Pure arithmetic over the CoreAudio constants, so it needs no fixture and
    /// pins the one decision every caller downstream branches on.
    @Test("lossless codecs are the ones that are lossless, and no others")
    func losslessFormatTable() {
        #expect(AudioStreamInfo.isLosslessFormat(kAudioFormatLinearPCM))
        #expect(AudioStreamInfo.isLosslessFormat(kAudioFormatAppleLossless))
        #expect(AudioStreamInfo.isLosslessFormat(kAudioFormatFLAC))
        #expect(!AudioStreamInfo.isLosslessFormat(kAudioFormatMPEG4AAC))
        #expect(!AudioStreamInfo.isLosslessFormat(kAudioFormatMPEGLayer3))
        #expect(!AudioStreamInfo.isLosslessFormat(kAudioFormatOpus))
    }

    @Test("codec names are spelled the way the familiar tools spell them")
    func codecNames() {
        #expect(AudioStreamInfo.commonCodecName(forFormatID: kAudioFormatMPEG4AAC, fourCC: "aac ")
            == "aac")
        #expect(AudioStreamInfo.commonCodecName(forFormatID: kAudioFormatMPEGLayer3, fourCC: ".mp3")
            == "mp3")
        #expect(AudioStreamInfo.commonCodecName(forFormatID: kAudioFormatAppleLossless, fourCC: "alac")
            == "alac")
        #expect(AudioStreamInfo.commonCodecName(forFormatID: kAudioFormatOpus, fourCC: "opus")
            == "opus")
        // An unrecognised code stays greppable rather than becoming "unknown".
        #expect(AudioStreamInfo.commonCodecName(forFormatID: 0x7A7A7A7A, fourCC: "ZZZZ") == "zzzz")
    }

    // MARK: - Fixture gate

    /// Generates a fixture, or turns a generation failure into a known issue
    /// with a legible reason — a machine without a working encoder should not
    /// report a green suite, nor a failure that looks like a bug in the code
    /// under test.
    private func fixture(_ name: String, _ make: () async throws -> URL) async -> URL? {
        do {
            return try await make()
        } catch {
            withKnownIssue("could not generate the fixture \"\(name)\" on this machine: \(error)") {
                Issue.record("fixture generation failed")
            }
            return nil
        }
    }
}
