import Foundation
import LatheCore
import LatheFixtures
import Testing

@testable import LatheAudio

/// Tests for the loudness probe, against clips generated by `LatheFixtures`.
///
/// The suite is serialised because every test encodes or decodes media; running
/// a dozen of those concurrently makes the machine the bottleneck and the
/// timings meaningless.
@Suite("Loudness probe", .serialized)
struct LoudnessProbeTests {

    private let probe = LoudnessProbe()

    /// Length of the sparse fixture. Long enough that 0.2 s of tone is diluted
    /// into invisibility by a whole-file mean, which is the entire point.
    private static let sparseSeconds: Double = 60
    private static let sparseAudio = FixtureAudio.sparseTone(
        hertz: 440, amplitude: 0.2, onsetSeconds: 0.5, lengthSeconds: 0.2
    )

    // MARK: - Thresholds

    /// Both thresholds sit above a realistic room-noise floor and below anything
    /// a listener would call audible. Pinning them means a careless edit shows up
    /// as a failure rather than as a silent change in classification.
    @Test("default thresholds are in the sane range")
    func thresholdsAreSane() {
        let thresholds = AudibilityThresholds.default
        #expect(thresholds.peakDBFS == -60)
        #expect(thresholds.shortTermRMSDBFS == -70)
        // The secondary RMS guard must be the more permissive of the two, or it
        // would never guard anything.
        #expect(thresholds.shortTermRMSDBFS < thresholds.peakDBFS)
        #expect(thresholds.peakDBFS < 0)
    }

    // MARK: - No track at all

    @Test("a file with no audio track is not a number and not an error")
    func noAudioTrack() async throws {
        guard let movie = await fixture("silent-video.mov", {
            try await FixtureLibrary.shared.movie(named: "silent-video.mov", audio: .none)
        }) else { return }

        let volume = try await probe.meanVolumeDB(url: movie)
        #expect(volume == .noAudioTrack)
        #expect(!volume.hasAudioTrack)
        #expect(volume.decibels == nil)
        // And the boolean answers the listener's question, for which a missing
        // track and a silent track are the same answer.
        #expect(try await probe.hasAudibleAudio(url: movie) == false)
    }

    @Test("a track of digital silence is distinguishable from having no track")
    func digitalSilenceIsItsOwnResult() async throws {
        guard let silent = await fixture("silence.wav", {
            try await FixtureLibrary.shared.wav(named: "silence.wav", seconds: 3, audio: .silence)
        }) else { return }

        let volume = try await probe.meanVolumeDB(url: silent)
        #expect(volume == .digitalSilence)
        #expect(volume.hasAudioTrack)      // ...unlike the case above
        #expect(volume.decibels == nil)
        #expect(volume.decibelsOrFloor == MeanVolume.digitalSilenceFloorDB)
        #expect(try await probe.hasAudibleAudio(url: silent) == false)
    }

    // MARK: - The measurement

    /// The mean is arithmetic, so it can be checked against arithmetic rather
    /// than against a number the implementation once produced.
    @Test("mean volume matches the level the samples were written at")
    func meanVolumeIsAccurate() async throws {
        let audio = FixtureAudio.tone(hertz: 440, amplitude: 0.5)
        guard let tone = await fixture("tone.wav", {
            try await FixtureLibrary.shared.wav(named: "tone.wav", seconds: 3, audio: audio)
        }) else { return }

        let expected = try #require(FixtureLibrary.expectedMeanVolumeDB(for: audio, seconds: 3))
        // A 0.5-amplitude sine has an RMS of 0.5/√2, i.e. 10·log₁₀(0.125) ≈ −9.03 dBFS.
        #expect(abs(expected - -9.03) < 0.1)

        let measured = try #require(try await probe.meanVolumeDB(url: tone).decibels)
        // 0.5 dB covers 16-bit quantisation and float accumulation order; it
        // does not cover an off-by-a-channel or a 20·log₁₀ mistake, which is
        // what this is guarding.
        #expect(abs(Double(measured) - expected) < 0.5)
    }

    @Test("mean volume is reported for a real container, not only for WAV")
    func meanVolumeThroughAAC() async throws {
        guard let movie = await fixture("loud-video.mov", {
            try await FixtureLibrary.shared.movie(
                named: "loud-video.mov", seconds: 2,
                audio: .tone(hertz: 440, amplitude: 0.5)
            )
        }) else { return }

        let measured = try #require(try await probe.meanVolumeDB(url: movie).decibels)
        // Wider than the WAV case on purpose: AAC is lossy, and its encoder
        // delay pads the track with silence that drags the mean down a little.
        #expect(measured > -20)
        #expect(measured < 0)
        #expect(try await probe.hasAudibleAudio(url: movie))
    }

    // MARK: - The sparse-audio cliff

    /// The reason this file has two methods instead of one.
    ///
    /// The clip is a minute long and contains 0.2 seconds of a clearly audible
    /// tone. Whole-file mean volume divides that energy by the whole minute and
    /// reports a number that any "is this silent" threshold would reject — while
    /// the file plainly is not silent. Both assertions below have to hold at
    /// once, or the pair of methods is not earning its keep.
    @Test("a sparse clip reads as quiet by mean volume and is still audible")
    func sparseAudioIsQuietOnAverageAndAudibleInFact() async throws {
        guard let sparse = await fixture("sparse.wav", {
            try await FixtureLibrary.shared.wav(
                named: "sparse.wav", seconds: Self.sparseSeconds, audio: Self.sparseAudio
            )
        }) else { return }

        let mean = try #require(try await probe.meanVolumeDB(url: sparse).decibels)

        // Below every threshold anyone sets for "silent" by mean volume. The
        // tone itself peaks at −14 dBFS; the mean lands more than 25 dB lower
        // purely because of the 59.8 seconds around it.
        #expect(mean < -35)

        // ...and yet:
        #expect(try await probe.hasAudibleAudio(url: sparse))

        // The gap between the two answers, stated numerically so a regression
        // that quietly reunited them fails here.
        let scan = try await probe.audibilityScan(url: sparse)
        #expect(scan.loudestWindowPeakDBFS > AudibilityThresholds.default.peakDBFS)
        #expect(scan.loudestWindowPeakDBFS - mean > 20)
    }

    @Test("the same sparse clip, with the tone at the very end, is still audible")
    func sparseAudioAtTheEnd() async throws {
        // Sound can start at 9:58. A probe that sampled the first few seconds
        // and gave up would pass every other test in this file and fail this
        // one.
        let audio = FixtureAudio.sparseTone(
            hertz: 440, amplitude: 0.2,
            onsetSeconds: Self.sparseSeconds - 0.4, lengthSeconds: 0.2
        )
        guard let sparse = await fixture("sparse-tail.wav", {
            try await FixtureLibrary.shared.wav(
                named: "sparse-tail.wav", seconds: Self.sparseSeconds, audio: audio
            )
        }) else { return }

        #expect(try await probe.hasAudibleAudio(url: sparse))
    }

    // MARK: - Early exit

    /// Asserted by counting frames, not by timing.
    ///
    /// A wall-clock comparison would test the machine. The scan reports how many
    /// sample frames it actually examined, so "it stopped early" is checked as
    /// arithmetic: a tone starting at 0.5 s into a 60-second file must be
    /// decided inside the first second or two, not after 2.6 million frames.
    @Test("audibility stops reading as soon as it has an answer")
    func audibilityExitsEarly() async throws {
        guard let sparse = await fixture("sparse.wav", {
            try await FixtureLibrary.shared.wav(
                named: "sparse.wav", seconds: Self.sparseSeconds, audio: Self.sparseAudio
            )
        }) else { return }

        let scan = try await probe.audibilityScan(url: sparse)
        #expect(scan.isAudible)
        #expect(scan.framesAvailable > 2_000_000)
        #expect(scan.framesExamined < scan.framesAvailable / 10,
                "examined \(scan.framesExamined) of \(scan.framesAvailable) frames")
    }

    @Test("a silent file is scanned to the end, because it has to be")
    func silenceIsScannedInFull() async throws {
        guard let silent = await fixture("silence-long.wav", {
            try await FixtureLibrary.shared.wav(
                named: "silence-long.wav", seconds: 5, audio: .silence
            )
        }) else { return }

        let scan = try await probe.audibilityScan(url: silent)
        #expect(!scan.isAudible)
        // Within one window of the whole file: there is no correct way to
        // shorten this, and pretending otherwise is how sound at 9:58 gets lost.
        #expect(scan.framesExamined >= scan.framesAvailable - UInt64(FixtureLibrary.sampleRate / 2))
    }

    // MARK: - Thresholds

    @Test("the RMS guard rejects a click that the peak alone would accept")
    func singleClickIsRejectedByTheRMSGuard() async throws {
        // One sample at full scale inside three seconds of silence. Its peak is
        // 0 dBFS — as loud as digital audio gets — so any peak-only test calls
        // it audible. Spread over a 400 ms window its RMS is about −42 dBFS,
        // which is what the second threshold is for.
        guard let click = await fixture("click.wav", {
            try await FixtureLibrary.shared.wav(
                named: "click.wav", seconds: 3,
                audio: .click(amplitude: 1.0, atSeconds: 1.0)
            )
        }) else { return }
        guard let tone = await fixture("sparse.wav", {
            try await FixtureLibrary.shared.wav(
                named: "sparse.wav", seconds: Self.sparseSeconds, audio: Self.sparseAudio
            )
        }) else { return }

        // The default thresholds are deliberately permissive — the type's own
        // documentation says to tune them on a real corpus — so this pins a
        // stricter pair and shows the guard doing its job: the click is
        // rejected and 0.2 s of real tone is not.
        let strict = AudibilityThresholds(peakDBFS: -60, shortTermRMSDBFS: -35)
        #expect(try await probe.audibilityScan(url: click, thresholds: strict).isAudible == false)
        #expect(try await probe.audibilityScan(url: tone, thresholds: strict).isAudible)

        // And the click's peak really is the thing that would have fooled a
        // peak-only test.
        let peakOnly = try await probe.audibilityScan(url: click)
        #expect(peakOnly.loudestWindowPeakDBFS > -1)
    }

    // MARK: - Bad input

    @Test("a file that is not media fails, rather than reporting silence")
    func notMediaThrows() async throws {
        guard let url = await fixture("not-media.wav", {
            try await FixtureLibrary.shared.notMedia(named: "not-media.wav")
        }) else { return }

        await #expect(throws: LatheError.self) {
            _ = try await probe.meanVolumeDB(url: url)
        }
    }

    @Test("a missing file fails as a read error")
    func missingFileThrows() async throws {
        let missing = await FixtureLibrary.shared.scratchURL(named: "definitely-absent.wav")
        await #expect(throws: LatheError.self) {
            _ = try await probe.meanVolumeDB(url: missing)
        }
    }

    // MARK: - Fixture gate

    /// Generates a fixture, or turns a generation failure into a known issue
    /// with a legible reason.
    ///
    /// A machine without a working audio or video encoder should not report a
    /// green suite, and should not report a failure that looks like a bug in the
    /// probe either.
    private func fixture(_ name: String, _ make: () async throws -> URL) async -> URL? {
        do {
            return try await make()
        } catch {
            withKnownIssue("could not generate the fixture \"\(name)\" on this machine: \(error)") {
                Issue.record("fixture generation failed")
            }
            return nil
        }
    }
}
